language: swift
osx_image: xcode11.1

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - sed -i -e 's/<#CLIENT ID#>/""/g' TinkConnectExample/Constants.swift
  - xcodebuild -project TinkConnectExample.xcodeproj -scheme "TinkConnectExample" -sdk iphonesimulator clean build
